title: "Tick-virology Lab : Petit lab"
author: "Marine Petit"
description: "University of Surrey, School of Biosciences"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true           # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title : "About the Fantas-Ticks"}
  - {file: "CV.md", title : "Marine CV"}
  - {title:"Science Communication", file: "Science outreach.md"}
  - {title: "Research Interests", file: "Research_project.md"}
  - { title: "Publications", file: "publication.md"}
  - {title: "R scripts", file: "R_scripts.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:petit.marine75@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/mpetit75"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
