title: "Petit lab"
author: "Marine Petit"
description: "Lecturer in Virology and Group Leader at the University of Surrey"
      
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true           # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "CV.md", title : "Marine Petit"}
  - {file: "README.md", title : "The Fantas-ticks Team"}
  - {title: "Blog", file: "blog.md"}
  - { title: "Publications", file: "publication.md"}
  - {title: "R scripts", file: "R_scripts.md"}
  - {title: "Research Project", file: "TICKITS.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:petit.marine75@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/mpetit75"}
  

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
